services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: yatrasathi:latest
    restart: unless-stopped
    environment:
      WATCHPACK_POOLING: true
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    restart: unless-stopped
    command: "-d 1"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: "http host.docker.internal:3000 --domain=${NGROK_DOMAIN} --log=stdout"
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app

volumes:
  db_data:
  node_modules:
