services:
  postgres:
    image: postgres:17
    command: "-d 1"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yatrasathi

  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: "http host.docker.internal:3000 --domain=${NGROK_DOMAIN} --log=stdout"
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

volumes:
  db_data:
